API_KEY = 'fdgsfdgsfdgdsfgdfgfd'
MPAN = 'fgfdgdfgdfg'
SERIAL = 'nncbvncbvn'
TIMESTAMP_PATH = 'sdfgsfdgfds'
CONSUMPTION_FILE = 'fdsfdsg.json'
TARIFF_TIMESTAMP_PATH = 'sdfsdgfdsgfd'
TARIFF_FILE = 'dfdgfdsgd'
